# Generated by Django 4.2.1 on 2023-06-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='User',
            new_name='user',
        ),
    ]
