# Generated by Django 4.2.1 on 2023-05-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecnoBlog_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
