# Generated by Django 4.2.1 on 2023-05-29 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TecnoBlog_App', '0002_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
