# Generated by Django 4.2.1 on 2023-06-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecnoBlog_App', '0003_articulo_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcercaDeMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='sobre_mi/')),
            ],
        ),
    ]
